name: habit_app
description: "Habit Tracker App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+32

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  provider: ^6.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  intl: ^0.19.0
  firebase_core: ^2.25.3
  quiver: ^3.2.1
  go_router: ^13.2.0
  package_info_plus: ^5.0.1
  flutter_email_sender: ^6.0.2
  kr_pull_down_button: ^1.0.1
  flutter_ringtone_player: ^4.0.0+2
  flutter_animate: ^4.5.0
  table_calendar: ^3.1.0
  flutter_local_notifications: ^16.3.3
  flutter_timezone: ^1.0.8
  in_app_purchase: ^3.1.13
  in_app_purchase_storekit: ^0.3.8+1
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.3.0
  lottie: ^3.1.0
  flutter_native_splash: ^2.3.10
  tutorial_coach_mark: ^1.2.11
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/emojis/
    - assets/lotties/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
    - family: WalterTurncoat
      fonts:
        - asset: assets/fonts/WalterTurncoat-Regular.ttf
