// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6OQ_rm8mRwuKa9H5G_fBwljNTAqoblk',
    appId: '1:527508969738:ios:5052cb99ebf02979a782f3',
    messagingSenderId: '527508969738',
    projectId: 'zest-habit',
    storageBucket: 'zest-habit.appspot.com',
    iosClientId: '527508969738-hba06sdoi48fp6t9c7h4tvic4l3220em.apps.googleusercontent.com',
    iosBundleId: 'dev.jeanie.habitApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-6myJW1qM-35lLG-kqMkLQdvhkcxDCA',
    appId: '1:527508969738:web:dd549eec33223d75a782f3',
    messagingSenderId: '527508969738',
    projectId: 'zest-habit',
    authDomain: 'zest-habit.firebaseapp.com',
    storageBucket: 'zest-habit.appspot.com',
    measurementId: 'G-TCCZHH6W7Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6OQ_rm8mRwuKa9H5G_fBwljNTAqoblk',
    appId: '1:527508969738:ios:5052cb99ebf02979a782f3',
    messagingSenderId: '527508969738',
    projectId: 'zest-habit',
    storageBucket: 'zest-habit.appspot.com',
    iosClientId: '527508969738-hba06sdoi48fp6t9c7h4tvic4l3220em.apps.googleusercontent.com',
    iosBundleId: 'dev.jeanie.habitApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU0qKT4avaEiqf0tPSL5ILP4rqPWqhBBI',
    appId: '1:527508969738:android:0eb9966ff0307afca782f3',
    messagingSenderId: '527508969738',
    projectId: 'zest-habit',
    storageBucket: 'zest-habit.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm-6myJW1qM-35lLG-kqMkLQdvhkcxDCA',
    appId: '1:527508969738:web:3cc12eabd6b45fefa782f3',
    messagingSenderId: '527508969738',
    projectId: 'zest-habit',
    authDomain: 'zest-habit.firebaseapp.com',
    storageBucket: 'zest-habit.appspot.com',
    measurementId: 'G-4SFLD3LZKN',
  );

}